#配置端口号和访问前缀
server:
  port: 8080
  servlet:
    context-path: /ybb

#数据库配置
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/ybb?useUnicode=true&characterEncoding=utf8
      username:
      password:
      driverClassName: com.mysql.cj.jdbc.Driver

#配置日志
logging:
  #配置日志文件路径
  level:
    org.springfromework.web: info
  file: /usr/TomCat/logs/ybb.log